### ISSUE TITLE
Problem with testinstall/strings.tst

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/homebrew-gap#2]
`brew test gap-system/homebrew-gap/gap` fails with the following diffs:
```
testing: /usr/local/Cellar/gap/4.10.1/libexec/tst/testinstall/strings.tst
########> Diff in /usr/local/Cellar/gap/4.10.1/libexec/tst/testinstall/strings\
.tst:44
# Input is:
x:="\0xFF";
# Expected output:
"\377"
# But found:
""
########
########> Diff in /usr/local/Cellar/gap/4.10.1/libexec/tst/testinstall/strings\
.tst:48
# Input is:
x:="A string with \0xFF Hex stuff \0x42 in it";
# Expected output:
"A string with \377 Hex stuff B in it"
# But found:
"A string with ? Hex stuff B in it"
########
########> Diff in /usr/local/Cellar/gap/4.10.1/libexec/tst/testinstall/strings\
.tst:189
# Input is:
List("abcxyzABCXYZ\n\t !019?\377\000$", LowercaseChar);
# Expected output:
"abcxyzabcxyz\n\t !019?\377\000$"
# But found:
"abcxyzabcxyz\n\t !019??\000$"
########
########> Diff in /usr/local/Cellar/gap/4.10.1/libexec/tst/testinstall/strings\
.tst:191
# Input is:
List("abcxyzABCXYZ\n\t !019?\377\000$", UppercaseChar);
# Expected output:
"ABCXYZABCXYZ\n\t !019?\377\000$"
# But found:
"ABCXYZABCXYZ\n\t !019??\000$"
########
########> Diff in /usr/local/Cellar/gap/4.10.1/libexec/tst/testinstall/strings\
.tst:193
# Input is:
UppercaseString("abcxyzABCXYZ\n\t !019?\377\000$");
# Expected output:
"ABCXYZABCXYZ\n\t !019?\377\000$"
# But found:
"ABCXYZABCXYZ\n\t !019??\000$"
########
########> Diff in /usr/local/Cellar/gap/4.10.1/libexec/tst/testinstall/strings\
.tst:195
# Input is:
LowercaseString("abcxyzABCXYZ\n\t !019?\377\000$");
# Expected output:
"abcxyzabcxyz\n\t !019?\377\000$"
# But found:
"abcxyzabcxyz\n\t !019??\000$"
########
```
As said in https://github.com/Homebrew/homebrew-core/pull/36156, the same issue has been observed on SPARC Solaris 11 (https://github.com/gap-system/gap/issues/2194) and NixOS (https://github.com/gap-system/gap/issues/3152). 

If I test GAP using 

    /usr/local/Cellar/gap/4.10.1/bin/gap -r -A /usr/local/Cellar/gap/4.10.1/libexec/tst/testinstall.g

without calling `brew test`, then the test passes without errors.

Since https://github.com/gap-system/gap/issues/2194 is marked as "wontfix", unless we figure out why `brew test` triggers this and which workaround to use, we can advise to the users to test it like http://www.gap-system.org/Download/index.html says, with

    Read( Filename( DirectoriesLibrary("tst"), "testinstall.g" ));;

**Comment by dimpase** [comment]
I gather it's either the locale settings, or something to do with curses/termcap, or both. See also https://github.com/gap-system/gap/issues/3426

**Comment by dimpase** [comment]
Try starting GAP as follows
```
LC_CTYPE=en_US.UTF-8 ./gap
```
At least on OpenBSD this fixes it:
```
gap> "\377";
"\377"
```
instead of (with `LC_CTYPE=C`)
```
gap> "\377";
"�"
```

**Comment by dimpase** [comment]
In fact, even on Linux,
```
$ LC_CTYPE=C gap
...
gap> "\377";
"�"
```

**Comment by olexandr-konovalov** [comment]
Thanks @dimpase - the key was to replace LC_ALL by LC_CTYPE. Now tests pass.
