### ISSUE TITLE
gap or gap.sh

### ISSUE THREAD

**Issue by stevelinton** [gap-system/homebrew-gap#4]
I notice that the symlink is made to the `gap` binary rather than to `gap.sh`. Generally, I think the latter is preferred

**Comment by olexandr-konovalov** [comment]
This relies on the ability to call the binary directly - at some point someone (@ChrisJefferson or @fingolfin IIRC?) added it as an experiment, and it seems to work.

**Comment by fingolfin** [comment]
It works, and is fully supported, so it isn't an experiment (anymore) really

**Comment by olexandr-konovalov** [comment]
@fingolfin and the thing that it does not work on Windows is perhaps only because of the location of DLLs in another directory.

**Comment by olexandr-konovalov** [comment]
So I guess we may close this?
